spring:
  application:
    name: file-manager-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: 8080

resources:
  security:
    cryptography:
      encrypt-algorithm: AES
      key-size: 256
  volume:
    upload:
      directory-name: updatedFiles
    files:
      name-separator: .